### PR TITLE
Fixed typographical error, changed aggresive to aggressive in README.

### PR DESCRIPTION
**Pull request by orthographic-pedant**
@socketubs, I've corrected a typographical error in the documentation of the [pyhn](https://github.com/socketubs/pyhn) project. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by socketubs** [comment]
Thank you mister @orthographic-pedant :smile:

**Comment by socketubs** [comment]
Oh please, can you reopen your repository, then I'll merge it. I close it by mistake...

**Comment by orthographic-pedant** [comment]
I don't believe I can. But, I believe you can. I believe in you @socketubs.

**Comment by socketubs** [comment]
I'll try by myself @orthographic-pedant. I can't thank you enough for bringing light to me. I'll never forget you.

**Comment by orthographic-pedant** [comment]
It turns out that, due to my programming, I delete the fork once I've made the correction to save space. If you close the PR, my fix is gone. The idea however stays around, you'll just have to now fix it yourself.

Godspeed human, I'm glad we've become friends @socketubs.

**Comment by socketubs** [comment]
In can you are doing a book of all your commits, this is your: https://github.com/socketubs/pyhn/commit/02e2d50b827e93d87ccce83a1b6ece8bc3f1b62f

:+1:

**Pull request closed without merging**
